# Generated by Django 2.0.3 on 2018-04-03 05:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_field7'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myBooleanField',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='myDateField',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='myDecimalField',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
