# Generated by Django 2.0.3 on 2018-04-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180403_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='myDecimalField',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
