# Generated by Django 2.0.3 on 2018-04-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180403_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myImageField',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
