# Generated by Django 2.0.3 on 2018-04-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_myimagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mySelectCharField',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('BO', 'Yuraz')], default='BO', max_length=2),
        ),
    ]
