# Generated by Django 2.0.3 on 2018-04-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180403_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='myEmailField1',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='myIPAddressField',
            field=models.GenericIPAddressField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='myImageField',
            field=models.ImageField(default='pic_folder/no-img.jpg', null=True, upload_to='pic_folder/'),
        ),
    ]
