# Generated by Django 2.0.3 on 2018-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180403_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='myURLField',
            field=models.URLField(default='', null=True),
        ),
    ]
