# Generated by Django 2.0.3 on 2018-04-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='field1',
            field=models.CharField(default='', max_length=55),
        ),
    ]
