# Generated by Django 2.0.3 on 2018-04-03 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20180403_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
