# Generated by Django 2.0.3 on 2018-04-03 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180403_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Редактор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Короткое примечание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='field7',
            field=models.CharField(default='', max_length=210, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='myBooleanField',
            field=models.BooleanField(default=True, verbose_name='Книга на русском'),
        ),
        migrations.AlterField(
            model_name='post',
            name='myDateField',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Просто дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='myDecimalField',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Вес в кг'),
        ),
        migrations.AlterField(
            model_name='post',
            name='myEmailField1',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Почта 1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='myEmailField2',
            field=models.EmailField(default='mail@mail.ru', max_length=254, verbose_name='Почта 2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='mySelectCharField',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('BO', 'Yuraz')], default='BO', max_length=2, verbose_name='Рецензент'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='Название !', max_length=250, verbose_name='Название'),
        ),
    ]
