# Generated by Django 2.0.3 on 2018-04-03 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180403_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='Напишите кто редактор', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='Обязательно укажите название', max_length=250, verbose_name='Название'),
        ),
    ]
